spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin
      database: ${MONGO_DATABASE}

stripe:
  pb-key: ${STRIPE_PB_KEY}
  secret-key: ${STRIPE_SECRET_KEY}