spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/admin
      database: ${MONGO_DATABASE}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}

jwt:
  secret-key: ${PLUGIN_SECRET_KEY}